myblogsteps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('quiz.urls', namespace="quiz")),
    url(r'^quiz/', include('quiz.urls', namespace="quiz")),
]

quiz/urls.py
from django.conf.urls import patterns, url
from quiz import views as quiz_view


urlpatterns = patterns('quiz.view',
    url(r'^$', quiz_view.index, name='index'),
    url(r'^submit/$', quiz_view.submit , name='submit'),
    url(r'^question/(?P<type_id>\d+)/$', quiz_view.cat_questions , name='cat_questions'),
    #url(r'^question/$', quiz_view.cat_questions , name='cat_questions'),
    url(r'^question_level/(?P<level_id>\d+)/$', quiz_view.level_questions, name="level_questions"),
    url(r'^login/$',quiz_view.login, name="login"),
    url(r'^exam/(?P<id>\d+)/$', quiz_view.exam, name="exam"),
)

quiz/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


enum = lambda *l: [(s,_(s)) for s in l]


class Level(models.Model):
    title = models.CharField(max_length=255)
    max_time = models.CharField(max_length=255)
    order = models.IntegerField(max_length=255)
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = "Quiz Level"
        verbose_name_plural = "Quiz Level"

class Type(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateField('Created Date')
    is_active = models.BooleanField()
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = 'Quiz type'
        verbose_name_plural = 'Quizes Type'

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    max_time = models.IntegerField ()
    type = models.ForeignKey('Type')
    position = models.IntegerField()
    created_date = models.DateField('created_date')
    is_active = models.BooleanField()
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = 'Quiz'
        verbose_name_plural = 'Quizes'

class Question_type(models.Model):
    title = models.CharField(max_length=255)
    created_date = models.DateField('created_date')
    is_active = models.BooleanField()
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = 'Question Type'
        verbose_name_plural = 'Questions Type'

class Question(models.Model):
    level = models.ForeignKey(Level)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    quiz = models.ForeignKey(Quiz)
    answer_description = models.CharField(max_length=255)
    question_type = models.ForeignKey(Question_type)
    position = models.IntegerField ()
    created_date = models.DateField('created_date')
    is_active = models.BooleanField()
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'

class Question_option(models.Model):
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=255)
    position=models.IntegerField()
    is_correct = models.BooleanField()
    def __unicode__(self):
        return self.text
    class Meta:
        verbose_name = 'Question Option'
        verbose_name_plural = 'Questions Option'

class User(models.Model):
    email = models.CharField(max_length=200)
    all_info = models.CharField(max_length=255)
    def __unicode__(self):
        return self.email
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'User'

class Attempted(models.Model):
    user = models.ForeignKey('user')
    question = models.ForeignKey('Question')
    option = models.ForeignKey('question_option')

class response(models.Model):
    attempt= models.ForeignKey(Attempted)
    user = models.ForeignKey('User')
    quiz = models.ForeignKey('Quiz')
    score  = models.IntegerField()
    quiz_attempt_date = models.DateField()
    time_taken = models.CharField(max_length=255)








# Create your models here.

quiz/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import render
from django.template import RequestContext, loader
from quiz.models import Question, Question_option, User, Attempted, Type, Quiz, Level
from django.shortcuts import render, get_object_or_404
from django import forms
from django.shortcuts import get_list_or_404
from django.forms import ModelForm
from django.core.mail import send_mail, BadHeaderError
import json
from django.core import serializers
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives

def index(request):
    level_all = Level.objects.all().order_by('order')
    type_all = Type.objects.all()
    return render(request, 'quiz/main-content.html',{'type_all':type_all,'level_all':level_all})


def cat_questions(request, type_id):
    type_all = Type.objects.all()
    quiz = get_object_or_404(Quiz, pk=type_id)
    if quiz.max_time > 60 :
        hour = quiz.max_time / 60
        min = quiz.max_time % 60
    else:
        hour = 0
        min = quiz.max_time
    return render(request, 'quiz/questions.html', {'hour':hour,'min':min, 'quiz':quiz,'type_all':type_all, 'type_id':type_id})

def level_questions(request, level_id):
    level = get_object_or_404(Level, pk=level_id)
    max_time = int(level.max_time)
    if max_time > 60:
        hour = max_time / 60
        min = max_time % 60
    else:
        hour = 0
        min = max_time
    return render(request, 'quiz/question-full.html', {'hour':hour,'min':min, 'level': level})

def login(request):

    if request.method  == 'POST':
        inputEmail = request.POST['inputEmail']
        inputUsername = request.POST['inputUsername']
        inputPassword = request.POST['inputPassword']
    user = User(email=inputEmail,all_info='')
    user.save()
    return render(request, 'quiz/logged-in.html',{'inputEmail':inputEmail})

def exam(request, id):
    level = get_object_or_404(Level, pk=id)
    return render(request, 'quiz/exam.html', {'id':id, 'level':level})


def submit(request):
    option_pk = []
    type_all = Type.objects.all()
    correct_answer_count = 0
    total_question = 0
    if request.method  == 'POST':
        if 'email' in request.POST:
            email = request.POST['email']
        if 'type_id' in request.POST:
            id = request.POST['type_id']
            quiz = get_object_or_404(Quiz,pk=id)
            question_attempted = quiz.question_set.all()
            level = 0
            template = 'quiz/submit.html'
        elif 'level_id' in request.POST:
            id = request.POST['level_id']
            level = get_object_or_404(Level,pk=id)
            question_attempted = level.question_set.all()
            template = 'quiz/submit-full.html'
            quiz = ''
        user = User(email=email,all_info='')
        user.save()
        #Get Question as per Quiz Type Attempted
        #Get Correct Answer Count

        for question in question_attempted:
            total_question = total_question + 1
            if('option'+str(question.id)) in request.POST:
                pk = request.POST['option'+str(question.id)]
                option = get_object_or_404(Question_option, pk=pk)
                test_attempted = Attempted(question_id=question.id,option_id=option.id,user_id=int(user.id))
                test_attempted.save()
                if(option.is_correct == 1):
                    if(option.id == test_attempted.option_id):
                        correct_answer_count = correct_answer_count + 1

        user_result = get_list_or_404(Attempted, user_id=user.id)
       # user_result =
        answer= []

        per = (float(correct_answer_count)/total_question)*100
        percentage = round(per,2)
        for result in user_result:
            answer.append(int(result.option_id))
        #return render(request, {'type_id':type_id})
        """try:
            subject, from_email, to = 'mybologsteps: Quiz Result', 'kritika.shrivastava90@gmail.com', email
            text_content = 'This is an important message.'
            html_content = render_to_string('quiz/the_template.html', {'answer':answer ,'correct_answer_count':correct_answer_count,'total_question':total_question})
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()

        except BadHeaderError:
            return HttpResponse('Invalid header found.')"""

        return render(request, template,{'count':option_pk, 'type_all':type_all, 'question_attempted':question_attempted,'user_id':user.id,'answer':answer ,'correct_answer_count':correct_answer_count,'total_question':total_question,'level':level, 'percentage':percentage, 'quiz':quiz})
    else:
        return index(request)

quiz/templates/quiz/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>There is some Error!! my error chencged :-(</p>
</body>
</html>

quiz/templates/quiz/exam.html
{% extends "quiz/index-full.html" %}
{% block title %}Test Skills{% endblock %}
{% block content %}
<body>

    <div class="brand">{{ level }} </div>
    <div class="address-bar">{{ level}} | {{ level.question_set.all.count }} Questions | {{ level.max_time }} min max Time | 75% to Pass</div>
 <!-- Navigation -->

    <div class="container">
      <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Topics Covered
                        <strong>{{ level }}</strong>
                    </h2>
                    <hr>
                    <hr class="visible-xs">
                    <div class="col-sm-12 col-lg-8 col-md-8">
                        <p>Instructions</p>
                        <ul>
                            <li>This skills test contains {{ level.question_set.all.count  }} multiple choice questions.</li>
                            <li>You have {{ level.max_time }} minutes to complete this skills test.</li>
                            <li>Make sure you attempt all the questions.</li>
                            <li>Do not use the 'Back' button in your browser while taking this skills test.</li>
                            <li>Modern web browsers improve the skills test experience, so make sure your browser is up to date.</li>
                            <li>The questions in the skills test are in the English language.</li>
                        </ul>

                    </div>
                    <div class="col-sm-12 col-lg-3 col-md-3 col-md-offset-1">
                        <div class="right-box">
                        <div class="exam-btn"><a href="/quiz/question_level/{{ id }}" class="btn btn-primary btn-success">Test Your Skills</a></div>
                        <div class="exam-btn"><a href="/quiz" class="btn btn-primary btn-plain">Back To Page</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->


{% endblock %}

quiz/templates/quiz/header-full.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'quiz/css/jquery.countdownTimer.css' %}" />
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'quiz/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'quiz/css/business-casual.css' %}" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="{% static 'quiz/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'quiz/js/quiz.js' %}"></script>
    <script type="text/javascript" src="{% static 'quiz/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src = "{% static 'quiz/js/jquery.countdownTimer.js' %}"></script>

</head>
<body>

quiz/templates/quiz/header-main.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />


<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'quiz/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'quiz/css/shop-homepage.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

quiz/templates/quiz/index-full.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>
<body>
{% include 'quiz/header-full.html' %}
<!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

quiz/templates/quiz/index.html
<!DOCTYPE html>
<html lang="en">
<head>
     <title>{% block title %}My amazing site{% endblock %}</title>
</head>
<body>
{% include 'quiz/header.html' %}
<!-- Page Content -->
    <div class="container">

        <div class="row">
             {% block sidebar %}  {% endblock %}

            <div class="col-md-9">
                {% block content %}{% endblock %}
            </div>


        </div>

    </div>
    {% include 'quiz/footer.html' %}


</body>

</html>

quiz/templates/quiz/level-questions.html
{{ level }}

    {% for question in level.question_set.all %}
        <li>{{ question }}</li>

        {% for option in question.question_option_set.all %}
            <ul>
                <li> {{ option }} </li>
            </ul>
        {% endfor %}


    {% endfor %}

quiz/templates/quiz/logged-in.html
logged in

quiz/templates/quiz/login.html
{{ checkin }}
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
       <form class="form-signin" method="post" action="/quiz/login/">
           {% csrf_token %}
        <h4 class="form-signin-heading">Sign up for free today!</h4>
            <label for="inputEmail" class="sr-only">Email address</label>
            <input type="email" id="inputEmail" name="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="" value="">
        <br>
            <label for="inputUsername" class="sr-only">Input Username</label>
            <input type="text" id="inputUsername" name="inputUsername" class="form-control" placeholder="Username" required="" autofocus="" value="">
        <br>
           <label for="inputPassword" class="sr-only">Password</label>
           <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Password" required="">
        <br>
         <!--  <div class="checkbox">
         <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>-->
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create Account</button>
      </form>
         <p style="text-align:center">Don't have an account? Sign Up!</p>
    </div>

  </div>
</div>

quiz/templates/quiz/question-full.html
{% extends "quiz/index-full.html" %}
{% block title %}Test Skills{% endblock %}
{% block content %}
<div class="row col-md-1 col-sm-3">
    <div id="hm_timer">
        <span id="hours">{{ hour }}</span>
        <span  id="min">{{ min }}</span>
    </div>
</div>
{% load staticfiles %}
<a href="#" class="scrollToTop"><img src="{% static 'quiz/images/scroll-to-top.jpg' %}" alt="scroll to top"></a>
<div class="enclosed col-md-10 col-lg-10 col-sm-9">
    <div class="brand">{{ level }}</div>
    <div class="address-bar">{{ level.question_set.all.count }} Questions| {{ level.max_time }} Min | 75% required to pass</div>
     <form method="POST" action="{% url 'quiz:submit' %}">
          {% csrf_token %}
           <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModalLabel">Enter Detail</h4>
                      </div>
                      <div class="modal-body">
                          <div class="form-group">
                            Email:<input type="text" class="form-control" name="email">
                          </div>
                     </div>
                      <div class="modal-footer">
                          <input type="submit" name="submit" class="btn btn-primary" value="View Results">
                      </div>
                    </div>
                  </div>
           </div>
        <div class="">
            <div class="row">

                <div class="box">
                    <div class="col-lg-11">
                            {% for question in level.question_set.all %}

                             <div class="question question-full">{{ forloop.counter }}) {{ question }}
                                 {% if question.description %}
                                 <div class="description">{{ question.description | safe }}</div>
                                    {% endif %}
                                 <br>
                                 <div class="row">
                                    {% for option in question.question_option_set.all  %}
                                        <div class="option col-md-9 pull-left">
                                                {{ forloop.counter }})
                                            <label class="radio-inline">
                                                <input type="radio" class="radio" name="option{{option.question_id}}" id="option2{{forloop.counter}}" value="{{ option.id}}">
                                                {{ option.text }}
                                            </label>
                                        </div>
                                    {% endfor %}

                                 </div>
                            </div>
                         {% endfor %}
                        <input type="hidden" name="level_id" value="{{ level.id }}">
                        <button type="button" id="btnfull" class="btn btn-primary" data-target="#exampleModal" data-toggle="modal"  data-backdrop="static" data-keyboard="false">Submit</button>
                    </div>
                </div>
            </div>
        </div>
     </form>
    <!-- /.container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-9 text-center">
                    <p>Copyright &copy; myblogsteps 2015</p>
                </div>
            </div>
        </div>
    </footer>
</div>
{% endblock %}

quiz/templates/quiz/questions.html
{% extends "quiz/index.html" %}
{% block title %}My amazing blog{% endblock %}
{% block sidebar %} {% include 'quiz/sidebar.html' %} {% endblock %}
{% block content %}
<div class="row">
    <div id="hm_timer">
        <span id="hours">{{ hour }}</span>
        <span  id="min">{{ min }}</span>
    </div>
</div>
{% load staticfiles %}
<a href="#" class="scrollToTop"><img src="{% static 'quiz/images/scroll-to-top.jpg' %}" alt="scroll to top"></a>

    <div class="brand">{{ quiz.type }} </div>
    <div class="address-bar">{{ quiz}} | {{ quiz.question_set.all.count }} Questions | {{ quiz.max_time }} max Time | 75% to Pass</div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
          <form method="POST" action="{% url 'quiz:submit' %}">
              {% csrf_token %}
              <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModalLabel">Enter Detail</h4>
                      </div>
                      <div class="modal-body">
                          <div class="form-group">
                            Email:<input type="text" class="form-control" name="email">
                          </div>
                     </div>
                      <div class="modal-footer">
                          <input type="submit" name="submit" class="btn btn-primary" value="View Results">
                      </div>
                    </div>
                  </div>
              </div>
             {% if quiz %}
                    {% for ques in quiz.question_set.all%}
                        <div class="question">
                            {% if ques.is_active > 0 %}
                                {{ forloop.counter }}) {{ques.title}}
                                {% if quest.description %}
                                <div class="question-description">{{ ques.description | safe }}</div>
                                <br>
                                {% endif %}
                                {% for option in ques.question_option_set.all %}
                                <div class="option">{{ forloop.counter }})
                                <label class="radio-inline">
                                    <input type="radio" name="option{{option.question_id}}" id="option1{{forloop.counter}}" value="{{ option.id}}">
                                    {{ option.text }}
                                </label>
                                </div>
                                {% endfor %}
                            {%  endif %}
                        </div>
                    {% endfor %}
               <input type="hidden" name="type_id" value="{{ type_id }}">
               <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Submit</button>
          </form>
            {% else %}
                <p>No Question Found</p>
            {% endif %}

</div>
{% endblock %}

quiz/templates/quiz/sidebar.html
<div class="col-md-3" id="sidebar">
                <p class="lead">Quiz Name</p>
                <div class="list-group">
                </div>

            <div class="panel-group" id="accordion">
                {% for type in type_all %}
                  <div class="panel panel-default">
                    <div class="panel-heading ">
                      <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne{{type}}">
                          {{ type}}
                        </a>
                      </h4>
                    </div>
                    <div id="collapseOne{{type}}" class="panel-collapse collapse">
                      <div class="panel-body">
                          <ul class="list-unstyled">
                              {% for subcat in type.quiz_set.all%}
                                <li> <a class="side_link" href="/quiz/question/{{ subcat.id }}">{{ subcat.title }}</a></li>
                              {% endfor %}
                          </ul>

                      </div>
                    </div>
                  </div>
                 {% endfor %}
            </div>
    </div>

quiz/templates/quiz/submit.html
{% extends "quiz/index.html" %}
{% block title %}My amazing blog{% endblock %}
{% block sidebar %} {% include 'quiz/sidebar.html' %} {% endblock %}
{% block content %}
  <div class="brand">{{ quiz.type }} </div>
 <div class="address-bar">{{ quiz}} | {{ quiz.question_set.all.count }} Questions | {{ quiz.max_time }} max Time | 75% to Pass</div>
<div class="row">
    <div class="col-md-12">
            <div class="col-md-4"></div>
            <div class="col-md-4" align="center">
                 <div class="result" align="center">
                    <p>Total number of question:  {{total_question}}</p>
                    <p>No of correct answers: {{ correct_answer_count}}</p>
                     <p>Your score is: {{percentage}} %</p>

                </div>
            </div>
           <div class="col-md-4"></div>
           <div class="col-md-6">
              {% for ques in question_attempted %}
                <div class="question">{{ forloop.counter }} {{ques.title}}
                    <br>
                    {% for option in ques.question_option_set.all %}
                        <div class="option">{{ forloop.counter }})
                        <label class="radio-inline">
                            <input type="radio" name="option{{option.question_id}}" id="option{{forloop.counter}}" value="{{ option.id}}">
                            {% if option.is_correct == 1 %}
                                <span style="color:green">{{ option.text }}</span>
                            {% else %}
                                {% for answer_id in answer %}
                                    {% if answer_id == option.id %}
                                        <span style="color:red">{{ option.text }}</span>
                                    {% endif %}
                                {% endfor %}
                                {% if option.id not in answer %}
                                    <span>{{ option.text }}</span>
                                {% endif%}
                            {% endif %}
                        </label>
                        </div>
                    {% endfor %}
                </div>
              {% endfor %}
           </div>
    </div>

</div>

{% endblock %}